#driver: memory # 连接驱动（内存缓存）

driver: redis # 连接驱动（redis缓存）

host: localhost # ip地址
port: 6379 # 端口
db: 0 #db
password: "5233" # 密码
timeout: 10s # 连接超时
read_timeout: 2s # 读超时
write_timeout: 2s # 写超时

